<?php
/**
 * Created by PhpStorm.
 * User: waiwai
 * Date: 2019-01-10
 * Time: 10:20
 *
 * @file Form example
 * https://www.drupal.org/docs/8/api/form-api/introduction-to-form-api
 */

namespace Drupal\wkm_test\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/*
 *
 */
class WkmTestExampleForm extends ConfigFormBase
{
  public function getFormId()
  {
    return "wkm_test.settings";
  }

  public function getEditableConfigNames()
  {
    return [
      'api_key' => null,
    ];
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $form['api_key'] = [
      '#type' => 'textfield',
      '#title' => 'API key',
      '#description' => 'Enter api key',
      '#default_value' =>  $this->config('wkm_test.settings')->get('api_key') ?? 'placeholder',
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function validateForm(array &$form, FormStateInterface $form_state)
  {
    dsm($form);
    dsm($form_state->getValues());

    if ($form_state->getValue('api_key') == 'placeholder') {
      $form_state->setErrorByName('api_key', 'You should enter an api key');
    }

    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    $api_key = $form_state->getValue('api_key');

    // save api key
    // $this->config('wkm_test.settings')->set('api_key', $api_key)->save();
    // The above example does not work. Config objects are immutable by default.
    // https://www.drupal.org/node/2407153
    \Drupal::configFactory()->getEditable('wkm_test.settings')->set('api_key', $api_key)->save();

    $stored_api_key = $this->config('wkm_test.settings')->get('api_key');

    dsm($stored_api_key, __FUNCTION__);

    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}