<?php
/**
 * Created by PhpStorm.
 * User: waiwai
 * Date: 2019-01-07
 * Time: 13:36
 */
namespace Drupal\marvel\Plugin\Block;


use Drupal\Core\Block\BlockBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\marvel\MarvelSalutation as MarvelSalutationService;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Marvel Salutation block.
 *
 * @Block(
 * id = "marvel_salutation_block",
 * admin_label = @Translation("Marvel salutation block"),
 * )
 */
class MarvelSalutationBlock extends BlockBase implements ContainerFactoryPluginInterface
{
  /**
   * @var MarvelSalutationService
   */
  protected $salutation;

  public function __construct(array $configuration, $plugin_id, $plugin_definition, MarvelSalutationService $salutation)
  {
    parent::__construct($configuration, $plugin_id, $plugin_definition);
    $this->salutation = $salutation;
  }

  /**
   * {@inheritdoc}
   *
   * @param ContainerInterface $container
   * @param array $configuration
   * @param string $plugin_id
   * @param mixed $plugin_definition
   * @return ContainerFactoryPluginInterface|MarvelSalutationBlock
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition)
  {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('marvel.salutation')
      );
  }

  public function blockForm($form, FormStateInterface $form_state)
  {
    $config = $this->getConfiguration();

    $form['enabled'] = array(
      '#type' => 'checkbox',
      '#title' => 'Enabled',
      '#description' => 'Check box if you want to enable feature.',
      '#default_value' => $config['enabled'],
    );

    return $form;
    //return parent::blockForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function blockSubmit($form, FormStateInterface $form_state)
  {
    $this->configuration['enabled'] = $form_state->getValue('enabled');
    //parent::blockSubmit($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function defaultConfiguration()
  {
    return [
      'enabled' => 1
    ];
    //return parent::defaultConfiguration(); // TODO: Change the autogenerated stub
  }

  public function build()
  {
    $config = $this->getConfiguration();
    $html =  ($config['enabled']) ? $this->salutation->getSalutation() : '';
    return [
      '#markup' => $html,
    ];

  }
}